# coding: utf-8

"""
    Quetzalcoatl API

    # TODO: an extensive documentation in CommonMark TODO   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quetzal.client.autogen
from quetzal.client.autogen.models.pagination_envelope import PaginationEnvelope  # noqa: E501
from quetzal.client.autogen.rest import ApiException


class TestPaginationEnvelope(unittest.TestCase):
    """PaginationEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginationEnvelope(self):
        """Test PaginationEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quetzal.client.autogen.models.pagination_envelope.PaginationEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
