# coding: utf-8

"""
    Quetzalcoatl API

    # TODO: an extensive documentation in CommonMark TODO   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quetzal.client.autogen
from quetzal.client.autogen.models.workspace_details_type import WorkspaceDetailsType  # noqa: E501
from quetzal.client.autogen.rest import ApiException


class TestWorkspaceDetailsType(unittest.TestCase):
    """WorkspaceDetailsType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceDetailsType(self):
        """Test WorkspaceDetailsType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quetzal.client.autogen.models.workspace_details_type.WorkspaceDetailsType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
