# coding: utf-8

"""
    Quetzalcoatl API

    # TODO: an extensive documentation in CommonMark TODO   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quetzal.client.autogen
from quetzal.client.autogen.models.file import File  # noqa: E501
from quetzal.client.autogen.rest import ApiException


class TestFile(unittest.TestCase):
    """File unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFile(self):
        """Test File"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quetzal.client.autogen.models.file.File()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
