# coding: utf-8

"""
    Quetzalcoatl API

    # TODO: an extensive documentation in CommonMark TODO   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quetzal.client.autogen
from quetzal.client.autogen.api.authentication_api import AuthenticationApi  # noqa: E501
from quetzal.client.autogen.rest import ApiException


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = quetzal.client.autogen.api.authentication_api.AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_app_api_auth_get_token(self):
        """Test case for app_api_auth_get_token

        Authenticate and obtain a token  # noqa: E501
        """
        pass

    def test_app_api_auth_logout(self):
        """Test case for app_api_auth_logout

        Logout and invalidate the existing token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
