# coding: utf-8

"""
    Quetzalcoatl API

    # TODO: an extensive documentation in CommonMark TODO   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Query(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'workspace_id': 'int',
        'dialect': 'str',
        'query': 'str',
        'results': 'InlineResponse2003Results'
    }

    attribute_map = {
        'id': 'id',
        'workspace_id': 'workspace_id',
        'dialect': 'dialect',
        'query': 'query',
        'results': 'results'
    }

    def __init__(self, id=None, workspace_id=None, dialect=None, query=None, results=None):  # noqa: E501
        """Query - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._workspace_id = None
        self._dialect = None
        self._query = None
        self._results = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if workspace_id is not None:
            self.workspace_id = workspace_id
        self.dialect = dialect
        self.query = query
        if results is not None:
            self.results = results

    @property
    def id(self):
        """Gets the id of this Query.  # noqa: E501

        Query identifier  # noqa: E501

        :return: The id of this Query.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Query.

        Query identifier  # noqa: E501

        :param id: The id of this Query.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def workspace_id(self):
        """Gets the workspace_id of this Query.  # noqa: E501

        Workspace identifier where the query operates  # noqa: E501

        :return: The workspace_id of this Query.  # noqa: E501
        :rtype: int
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id):
        """Sets the workspace_id of this Query.

        Workspace identifier where the query operates  # noqa: E501

        :param workspace_id: The workspace_id of this Query.  # noqa: E501
        :type: int
        """

        self._workspace_id = workspace_id

    @property
    def dialect(self):
        """Gets the dialect of this Query.  # noqa: E501

        Dialect of query  # noqa: E501

        :return: The dialect of this Query.  # noqa: E501
        :rtype: str
        """
        return self._dialect

    @dialect.setter
    def dialect(self, dialect):
        """Sets the dialect of this Query.

        Dialect of query  # noqa: E501

        :param dialect: The dialect of this Query.  # noqa: E501
        :type: str
        """
        if dialect is None:
            raise ValueError("Invalid value for `dialect`, must not be `None`")  # noqa: E501
        allowed_values = ["postgresql"]  # noqa: E501
        if dialect not in allowed_values:
            raise ValueError(
                "Invalid value for `dialect` ({0}), must be one of {1}"  # noqa: E501
                .format(dialect, allowed_values)
            )

        self._dialect = dialect

    @property
    def query(self):
        """Gets the query of this Query.  # noqa: E501

        Query in code as needed by the dialect  # noqa: E501

        :return: The query of this Query.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this Query.

        Query in code as needed by the dialect  # noqa: E501

        :param query: The query of this Query.  # noqa: E501
        :type: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def results(self):
        """Gets the results of this Query.  # noqa: E501


        :return: The results of this Query.  # noqa: E501
        :rtype: InlineResponse2003Results
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this Query.


        :param results: The results of this Query.  # noqa: E501
        :type: InlineResponse2003Results
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Query):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
