# coding: utf-8

"""
    Quetzalcoatl API

    # TODO: an extensive documentation in CommonMark TODO   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quetzal._auto_client
from quetzal._auto_client.models.metadata_query_type1 import MetadataQueryType1  # noqa: E501
from quetzal._auto_client.rest import ApiException


class TestMetadataQueryType1(unittest.TestCase):
    """MetadataQueryType1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQueryType1(self):
        """Test MetadataQueryType1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = quetzal._auto_client.models.metadata_query_type1.MetadataQueryType1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
