# coding: utf-8

"""
    Quetzalcoatl API

    # TODO: an extensive documentation in CommonMark TODO   # noqa: E501

    OpenAPI spec version: 0.3.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quetzal._auto_client
from quetzal._auto_client.api.data_api import DataApi  # noqa: E501
from quetzal._auto_client.rest import ApiException


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self):
        self.api = quetzal._auto_client.api.data_api.DataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_app_api_data_file_create(self):
        """Test case for app_api_data_file_create

        Add a new file  # noqa: E501
        """
        pass

    def test_app_api_data_file_details(self):
        """Test case for app_api_data_file_details

        Fetch file metadata or contents  # noqa: E501
        """
        pass

    def test_app_api_data_file_details_w(self):
        """Test case for app_api_data_file_details_w

        Fetch file metadata or contents  # noqa: E501
        """
        pass

    def test_app_api_data_file_fetch(self):
        """Test case for app_api_data_file_fetch

        List workspace files  # noqa: E501
        """
        pass

    def test_app_api_data_file_set_metadata(self):
        """Test case for app_api_data_file_set_metadata

        Rewrite file metadata  # noqa: E501
        """
        pass

    def test_app_api_data_file_update_metadata(self):
        """Test case for app_api_data_file_update_metadata

        Modify file metadata  # noqa: E501
        """
        pass

    def test_app_api_data_query_create(self):
        """Test case for app_api_data_query_create

        Prepare a query for a workspace  # noqa: E501
        """
        pass

    def test_app_api_data_query_details(self):
        """Test case for app_api_data_query_details

        Get details on query  # noqa: E501
        """
        pass

    def test_app_api_data_query_fetch(self):
        """Test case for app_api_data_query_fetch

        List all queries of a workspace  # noqa: E501
        """
        pass

    def test_app_api_data_workspace_commit(self):
        """Test case for app_api_data_workspace_commit

        Commit a workspace  # noqa: E501
        """
        pass

    def test_app_api_data_workspace_create(self):
        """Test case for app_api_data_workspace_create

        Create a new workspace  # noqa: E501
        """
        pass

    def test_app_api_data_workspace_delete(self):
        """Test case for app_api_data_workspace_delete

        Request deletion of a workspace  # noqa: E501
        """
        pass

    def test_app_api_data_workspace_details(self):
        """Test case for app_api_data_workspace_details

        Workspace details  # noqa: E501
        """
        pass

    def test_app_api_data_workspace_fetch(self):
        """Test case for app_api_data_workspace_fetch

        Get all workspaces  # noqa: E501
        """
        pass

    def test_app_api_data_workspace_scan(self):
        """Test case for app_api_data_workspace_scan

        Update workspace views  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
