# coding: utf-8

# flake8: noqa

"""
    Quetzalcoatl API

    Quetzal (short for Quetzalcoatl): an API to manage data files and their associated metadata.  # General documentation  ...  ## Concepts  * File * Metadata   Versioning too * Families * Workspace   Description, workspace states, data_url, etc. * Workspace views * Queries  # Errors  Quetzal uses standard HTTP error codes to indicate success or failure of its operations. The body of the response follows [RFC-7807](https://tools.ietf.org/html/rfc7807) to provide details on an error. For example:  ``` {   \"type\": \"https://quetz.al/problems/some-name\",   \"title\": \"Bad request.\",   \"status\": 400,   \"detail\": \"Incorrect foo due to missing bar.\",   \"instance\": \"/some_path/some_id\" } ```  # Versioning  API version | Changes ------------|--------- 0.1.0       | [API changes](https://quetz.al/docs/changelog#v0-1-0)   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# __version__ = "0.0.0"  # Commented by generate.sh

# import apis into sdk package
from quetzal._auto_client.api.authentication_api import AuthenticationApi
from quetzal._auto_client.api.data_api import DataApi
from quetzal._auto_client.api.public_api import PublicApi
from quetzal._auto_client.api.query_api import QueryApi
from quetzal._auto_client.api.workspace_api import WorkspaceApi

# import ApiClient
from quetzal._auto_client.api_client import ApiClient
from quetzal._auto_client.configuration import Configuration
# import models into sdk package
from quetzal._auto_client.models.base_metadata import BaseMetadata
from quetzal._auto_client.models.error import Error
from quetzal._auto_client.models.inline_object import InlineObject
from quetzal._auto_client.models.inline_object1 import InlineObject1
from quetzal._auto_client.models.inline_object2 import InlineObject2
from quetzal._auto_client.models.inline_object3 import InlineObject3
from quetzal._auto_client.models.inline_object4 import InlineObject4
from quetzal._auto_client.models.inline_response200 import InlineResponse200
from quetzal._auto_client.models.inline_response2001 import InlineResponse2001
from quetzal._auto_client.models.inline_response2001_results import InlineResponse2001Results
from quetzal._auto_client.models.inline_response2002 import InlineResponse2002
from quetzal._auto_client.models.inline_response2002_results import InlineResponse2002Results
from quetzal._auto_client.models.inline_response2003 import InlineResponse2003
from quetzal._auto_client.models.inline_response2004 import InlineResponse2004
from quetzal._auto_client.models.inline_response2004_results import InlineResponse2004Results
from quetzal._auto_client.models.inline_response201 import InlineResponse201
from quetzal._auto_client.models.inline_response_default import InlineResponseDefault
from quetzal._auto_client.models.metadata_by_family import MetadataByFamily
from quetzal._auto_client.models.paginated_files import PaginatedFiles
from quetzal._auto_client.models.paginated_queries import PaginatedQueries
from quetzal._auto_client.models.paginated_workspaces import PaginatedWorkspaces
from quetzal._auto_client.models.pagination_envelope import PaginationEnvelope
from quetzal._auto_client.models.query import Query
from quetzal._auto_client.models.query_no_results import QueryNoResults
from quetzal._auto_client.models.token import Token
from quetzal._auto_client.models.workspace import Workspace

# Added by generate.sh:
# Add a complete reference to the generator version:
# a git commit or Docker image ID used to generate this code with openapi-generator-cli
__openapi_generator_cli_version__ = "git-f3d47bbbec"
