# coding: utf-8

# flake8: noqa

"""
    Quetzalcoatl API

    Quetzal (short for Quetzalcoatl): an API to manage data files and their associated metadata.  # Overview  ...  ## Concepts  * File * Metadata   Versioning too * Families * Workspace   Description, workspace states, data_url, etc. * Workspace views * Queries  # Authentication  Authentication details  # Errors  Quetzal uses standard HTTP error codes to indicate success or failure of its operations. The body of the response follows [RFC-7807](https://tools.ietf.org/html/rfc7807) to provide details on an error. For example:  ``` {   \"type\": \"https://quetz.al/problems/some-name\",   \"title\": \"Bad request.\",   \"status\": 400,   \"detail\": \"Incorrect foo due to missing bar.\",   \"instance\": \"/some_path/some_id\" } ```  # Versioning  API version | Changes ------------|--------- 0.1.0       | [API changes](https://quetz.al/docs/changelog#v0-1-0)  # API reference   # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: support@quetz.al
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# __version__ = "0.0.0"  # Commented by generate.sh

# import apis into sdk package
from quetzal._auto_client.api.authentication_api import AuthenticationApi
from quetzal._auto_client.api.data_api import DataApi
from quetzal._auto_client.api.public_api import PublicApi
from quetzal._auto_client.api.query_api import QueryApi
from quetzal._auto_client.api.workspace_api import WorkspaceApi

# import ApiClient
from quetzal._auto_client.api_client import ApiClient
from quetzal._auto_client.configuration import Configuration
# import models into sdk package
from quetzal._auto_client.models.base_metadata import BaseMetadata
from quetzal._auto_client.models.error import Error
from quetzal._auto_client.models.file_contents import FileContents
from quetzal._auto_client.models.metadata_by_family import MetadataByFamily
from quetzal._auto_client.models.paginated_files import PaginatedFiles
from quetzal._auto_client.models.paginated_queries import PaginatedQueries
from quetzal._auto_client.models.paginated_workspaces import PaginatedWorkspaces
from quetzal._auto_client.models.pagination_envelope import PaginationEnvelope
from quetzal._auto_client.models.query import Query
from quetzal._auto_client.models.query_no_results import QueryNoResults
from quetzal._auto_client.models.token import Token
from quetzal._auto_client.models.workspace import Workspace

# Added by generate.sh:
# Add a complete reference to the generator version:
# a git commit or Docker image ID used to generate this code with openapi-generator-cli
__openapi_generator_cli_version__ = "git-f3d47bbbec"
